### ISSUE TITLE
AttributeError: __exit__

### ISSUE THREAD

**Issue by GabrielBigardi** [cymruu/python-tibia#2]
Hi, how are you doing?
I know it's been some time since you worked on this project, but it's something i find pretty interesting and i wan't to study.
However, i'm having this problem while trying to run it:

```
Traceback(most recent call last):
    File "bot.py", line 127, in <module>
        with socket.socket() as s:
AttributeError: __exit__
```

The line 127 is the function that connects to the server and send the packets.
I don't think it has something to do with the server, because it don't give me a timeout...

Thanks since now.

**Comment by cymruu** [comment]
Hi, make sure you're using Python 3.x.
